image: docker:19.03.12

stages:
  - unittest
  - build
  - inttest
  - release

variables:
  IMAGE_TAG_REF: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_VERSION: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

build:
  stage: build
  script:
    - apk add --update nodejs nodejs-npm jq
    - npm install
    - npm run build
    - 'echo "{\"version\": \"$(jq .version -r package.json)\"}" > dist/version.json'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $IMAGE_TAG_REF .
    - docker push $IMAGE_TAG_REF
  tags:
    - portal

release-image:
  stage: release
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG_REF
    - docker tag $IMAGE_TAG_REF $IMAGE_TAG_VERSION
    - docker push $IMAGE_TAG_VERSION
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - portal
