image: docker:19.03.12

variables:
  IMAGE_TAG_REF: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_VERSION: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

build:
  script:
    - apk add --update nodejs nodejs-npm
    - npm install
    - npm run build
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $IMAGE_TAG_REF .
    - docker push $IMAGE_TAG_REF
  tags:
    - portal